# Lab 2
## File 1

In [13]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

def euclidean_distance(a, b):
    return np.sqrt(sum(a-b)**2)

#Load dataset samples and split in test and training samples
iris = datasets.load_iris()
irisData = iris.data
irisTarget = iris.target
#Calculate standard score of data
z = (irisData - np.mean(irisData, axis=0)) / np.std(irisData, axis=0)
#print(z)
#Split samples and labels into test and training data
irisData_train, irisData_test, irisLabels_train, irisLabels_test = train_test_split(irisData, irisTarget, test_size=0.3, random_state=45)
print("Data_train = ", irisData_train)
print("Data_test = ", irisData_test)
print("Label_train = ", irisLabels_train)
print("Labels_test = ", irisLabels_test)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

## knn.py

In [27]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

class KNearestNeighbours():
    def __init__(self, X_train, Y_train, n_neighbours=5):
        self.X_train = X_train
        self.Y_train = Y_train
        self.n_neighbours = n_neighbours

    '''Returns the euclidean distance between a and b'''
    def euclidean_distance(self, a, b):
        return np.sqrt(np.sum((a-b)**2, axis=1))
    
    '''Returns the 5 shortest distances for all test values'''
    def kneighbours(self, X_test):
        points = []
        index_arr = []
        distance_arr = []
        #Iterate through all test samples
        for x in X_test:
            #Calculate euclidean distance and append to array
            point = self.euclidean_distance(x, self.X_train)
            points.append(point)
        #Iterate through the calculated distances
        for distance in points:
            #Add the index to each distance in the list
            en = enumerate(distance)
            #Save the 5 shortest distances for that test sample
            so = sorted(en, key=lambda x: x[1])[:self.n_neighbours]
            #Separate indexes from enumerate object
            indexes = [i[0] for i in so]
            #Separate distances from enumerate object
            distances = [i[1] for i in so]
            #Save indexes and distances to list
            index_arr.append(indexes)
            distance_arr.append(distances)
        return index_arr
    
    '''Returns the predicted y value of the test sample'''
    def predict(self, X_test):
        #Get the number and indexes of neighbours
        neighbours = self.kneighbours(X_test)
        y_preds = np.array([np.argmax(np.bincount(self.Y_train[neighbour])) for neighbour in neighbours])
        return y_preds

[[0.53338619 3.97412718 3.66570053 ... 1.39387913 4.02476156 5.06729927]
 [0.54697576 3.69050304 3.54422981 ... 1.55009443 3.7126811  4.86449785]
 [4.1880091  1.28578628 2.67880686 ... 4.70704597 1.13153107 2.12233987]
 ...
 [1.65160596 3.70153739 2.90871426 ... 2.5621376  4.17875708 5.5040961 ]
 [3.53490258 1.24250173 2.48521513 ... 4.08320965 1.04938721 2.28576881]
 [3.47437514 2.53399676 1.29593595 ... 4.43597053 3.67415129 5.3951229 ]]
[[87, 55, 20, 24, 4], [87, 22, 0, 24, 55], [49, 46, 78, 66, 77], [13, 11, 19, 71, 5], [30, 5, 88, 11, 19], [10, 92, 0, 42, 8], [91, 71, 5, 88, 13], [26, 36, 49, 78, 46], [85, 1, 32, 59, 62], [40, 98, 18, 69, 77], [20, 55, 24, 87, 31], [46, 77, 49, 98, 103], [99, 59, 32, 37, 85], [63, 7, 54, 53, 1], [62, 64, 85, 32, 28], [67, 30, 19, 11, 24], [18, 69, 77, 54, 98], [99, 32, 85, 37, 52], [87, 24, 55, 20, 4], [100, 15, 2, 59, 95], [6, 43, 101, 76, 44], [84, 48, 76, 16, 86], [86, 68, 90, 35, 103], [84, 79, 96, 65, 66], [4, 87, 55, 0, 8], [77, 54, 69, 46, 

## knntest.py

In [30]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
#knn.py contains the relevant Class KNearestNeighbours from the above cell
from knn import KNearestNeighbours

#Load dataset and split data and labels
iris = datasets.load_iris()
irisData = iris.data
irisTarget = iris.target

#Calculate standard score of data
z = (irisData - np.mean(irisData, axis=0)) / np.std(irisData, axis=0)

#Split samples and labels into test and training sets
irisData_train, irisData_test, irisLabels_train, irisLabels_test = train_test_split(z, irisTarget, test_size=0.3, random_state=45)

#Initialize instance of class
data = KNearestNeighbours(irisData_train, irisLabels_train, 7)

#Get predicted labels
prediction = data.predict(irisData_test)
print("Label prediction", prediction)
print("Actual Labels", irisLabels_test)

#Calculate accuracy [%]
accuracy = (np.sum(irisLabels_test == prediction) / len(irisLabels_test)) * 100
print("Accuracy: ", accuracy, "%")


Label prediction [0 0 2 0 0 0 0 2 2 2 0 2 2 2 1 0 2 2 0 1 1 2 2 1 0 2 1 1 0 1 1 1 1 2 0 2 0
 0 1 0 0 1 0 1 1]
Actual Labels [0 0 2 0 0 0 0 2 2 2 0 2 2 2 2 0 2 2 0 1 1 1 2 1 0 2 1 1 0 1 1 1 2 2 0 2 0
 0 1 0 0 1 0 1 1]
Accuracy:  93.33333333333333 %
